/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppVendasIndexRouteImport } from './routes/_authenticated/app.vendas.index'
import { Route as AuthenticatedAppSegurancaIndexRouteImport } from './routes/_authenticated/app.seguranca.index'
import { Route as AuthenticatedAppRhIndexRouteImport } from './routes/_authenticated/app.rh.index'
import { Route as AuthenticatedAppReciclaveisIndexRouteImport } from './routes/_authenticated/app.reciclaveis.index'
import { Route as AuthenticatedAppQualidadeIndexRouteImport } from './routes/_authenticated/app.qualidade.index'
import { Route as AuthenticatedAppProducaoIndexRouteImport } from './routes/_authenticated/app.producao.index'
import { Route as AuthenticatedAppOsIndexRouteImport } from './routes/_authenticated/app.os.index'
import { Route as AuthenticatedAppMelhoriaIndexRouteImport } from './routes/_authenticated/app.melhoria.index'
import { Route as AuthenticatedAppFiscalIndexRouteImport } from './routes/_authenticated/app.fiscal.index'
import { Route as AuthenticatedAppFinanceiroIndexRouteImport } from './routes/_authenticated/app.financeiro.index'
import { Route as AuthenticatedAppComprasIndexRouteImport } from './routes/_authenticated/app.compras.index'
import { Route as AuthenticatedAppSetorSetorRouteImport } from './routes/_authenticated/app.setor.$setor'
import { Route as AuthenticatedAppQualidadeInspecoesRouteImport } from './routes/_authenticated/app.qualidade.inspecoes'
import { Route as AuthenticatedAppQualidadeIdRouteImport } from './routes/_authenticated/app.qualidade.$id'
import { Route as AuthenticatedAppOsNovaRouteImport } from './routes/_authenticated/app.os.nova'
import { Route as AuthenticatedAppOsIdRouteImport } from './routes/_authenticated/app.os.$id'
import { Route as AuthenticatedAppAdminPageRouteImport } from './routes/_authenticated/app.admin.$page'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVendasIndexRoute =
  AuthenticatedAppVendasIndexRouteImport.update({
    id: '/app/vendas/',
    path: '/app/vendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSegurancaIndexRoute =
  AuthenticatedAppSegurancaIndexRouteImport.update({
    id: '/app/seguranca/',
    path: '/app/seguranca/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRhIndexRoute = AuthenticatedAppRhIndexRouteImport.update({
  id: '/app/rh/',
  path: '/app/rh/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReciclaveisIndexRoute =
  AuthenticatedAppReciclaveisIndexRouteImport.update({
    id: '/app/reciclaveis/',
    path: '/app/reciclaveis/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppQualidadeIndexRoute =
  AuthenticatedAppQualidadeIndexRouteImport.update({
    id: '/app/qualidade/',
    path: '/app/qualidade/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProducaoIndexRoute =
  AuthenticatedAppProducaoIndexRouteImport.update({
    id: '/app/producao/',
    path: '/app/producao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOsIndexRoute = AuthenticatedAppOsIndexRouteImport.update({
  id: '/app/os/',
  path: '/app/os/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMelhoriaIndexRoute =
  AuthenticatedAppMelhoriaIndexRouteImport.update({
    id: '/app/melhoria/',
    path: '/app/melhoria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFiscalIndexRoute =
  AuthenticatedAppFiscalIndexRouteImport.update({
    id: '/app/fiscal/',
    path: '/app/fiscal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroIndexRoute =
  AuthenticatedAppFinanceiroIndexRouteImport.update({
    id: '/app/financeiro/',
    path: '/app/financeiro/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppComprasIndexRoute =
  AuthenticatedAppComprasIndexRouteImport.update({
    id: '/app/compras/',
    path: '/app/compras/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSetorSetorRoute =
  AuthenticatedAppSetorSetorRouteImport.update({
    id: '/app/setor/$setor',
    path: '/app/setor/$setor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppQualidadeInspecoesRoute =
  AuthenticatedAppQualidadeInspecoesRouteImport.update({
    id: '/app/qualidade/inspecoes',
    path: '/app/qualidade/inspecoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppQualidadeIdRoute =
  AuthenticatedAppQualidadeIdRouteImport.update({
    id: '/app/qualidade/$id',
    path: '/app/qualidade/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOsNovaRoute = AuthenticatedAppOsNovaRouteImport.update({
  id: '/app/os/nova',
  path: '/app/os/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppOsIdRoute = AuthenticatedAppOsIdRouteImport.update({
  id: '/app/os/$id',
  path: '/app/os/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminPageRoute =
  AuthenticatedAppAdminPageRouteImport.update({
    id: '/app/admin/$page',
    path: '/app/admin/$page',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/$page': typeof AuthenticatedAppAdminPageRoute
  '/app/os/$id': typeof AuthenticatedAppOsIdRoute
  '/app/os/nova': typeof AuthenticatedAppOsNovaRoute
  '/app/qualidade/$id': typeof AuthenticatedAppQualidadeIdRoute
  '/app/qualidade/inspecoes': typeof AuthenticatedAppQualidadeInspecoesRoute
  '/app/setor/$setor': typeof AuthenticatedAppSetorSetorRoute
  '/app/compras/': typeof AuthenticatedAppComprasIndexRoute
  '/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
  '/app/fiscal/': typeof AuthenticatedAppFiscalIndexRoute
  '/app/melhoria/': typeof AuthenticatedAppMelhoriaIndexRoute
  '/app/os/': typeof AuthenticatedAppOsIndexRoute
  '/app/producao/': typeof AuthenticatedAppProducaoIndexRoute
  '/app/qualidade/': typeof AuthenticatedAppQualidadeIndexRoute
  '/app/reciclaveis/': typeof AuthenticatedAppReciclaveisIndexRoute
  '/app/rh/': typeof AuthenticatedAppRhIndexRoute
  '/app/seguranca/': typeof AuthenticatedAppSegurancaIndexRoute
  '/app/vendas/': typeof AuthenticatedAppVendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/$page': typeof AuthenticatedAppAdminPageRoute
  '/app/os/$id': typeof AuthenticatedAppOsIdRoute
  '/app/os/nova': typeof AuthenticatedAppOsNovaRoute
  '/app/qualidade/$id': typeof AuthenticatedAppQualidadeIdRoute
  '/app/qualidade/inspecoes': typeof AuthenticatedAppQualidadeInspecoesRoute
  '/app/setor/$setor': typeof AuthenticatedAppSetorSetorRoute
  '/app/compras': typeof AuthenticatedAppComprasIndexRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroIndexRoute
  '/app/fiscal': typeof AuthenticatedAppFiscalIndexRoute
  '/app/melhoria': typeof AuthenticatedAppMelhoriaIndexRoute
  '/app/os': typeof AuthenticatedAppOsIndexRoute
  '/app/producao': typeof AuthenticatedAppProducaoIndexRoute
  '/app/qualidade': typeof AuthenticatedAppQualidadeIndexRoute
  '/app/reciclaveis': typeof AuthenticatedAppReciclaveisIndexRoute
  '/app/rh': typeof AuthenticatedAppRhIndexRoute
  '/app/seguranca': typeof AuthenticatedAppSegurancaIndexRoute
  '/app/vendas': typeof AuthenticatedAppVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/$page': typeof AuthenticatedAppAdminPageRoute
  '/_authenticated/app/os/$id': typeof AuthenticatedAppOsIdRoute
  '/_authenticated/app/os/nova': typeof AuthenticatedAppOsNovaRoute
  '/_authenticated/app/qualidade/$id': typeof AuthenticatedAppQualidadeIdRoute
  '/_authenticated/app/qualidade/inspecoes': typeof AuthenticatedAppQualidadeInspecoesRoute
  '/_authenticated/app/setor/$setor': typeof AuthenticatedAppSetorSetorRoute
  '/_authenticated/app/compras/': typeof AuthenticatedAppComprasIndexRoute
  '/_authenticated/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
  '/_authenticated/app/fiscal/': typeof AuthenticatedAppFiscalIndexRoute
  '/_authenticated/app/melhoria/': typeof AuthenticatedAppMelhoriaIndexRoute
  '/_authenticated/app/os/': typeof AuthenticatedAppOsIndexRoute
  '/_authenticated/app/producao/': typeof AuthenticatedAppProducaoIndexRoute
  '/_authenticated/app/qualidade/': typeof AuthenticatedAppQualidadeIndexRoute
  '/_authenticated/app/reciclaveis/': typeof AuthenticatedAppReciclaveisIndexRoute
  '/_authenticated/app/rh/': typeof AuthenticatedAppRhIndexRoute
  '/_authenticated/app/seguranca/': typeof AuthenticatedAppSegurancaIndexRoute
  '/_authenticated/app/vendas/': typeof AuthenticatedAppVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/'
    | '/app/admin/$page'
    | '/app/os/$id'
    | '/app/os/nova'
    | '/app/qualidade/$id'
    | '/app/qualidade/inspecoes'
    | '/app/setor/$setor'
    | '/app/compras/'
    | '/app/financeiro/'
    | '/app/fiscal/'
    | '/app/melhoria/'
    | '/app/os/'
    | '/app/producao/'
    | '/app/qualidade/'
    | '/app/reciclaveis/'
    | '/app/rh/'
    | '/app/seguranca/'
    | '/app/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/admin/$page'
    | '/app/os/$id'
    | '/app/os/nova'
    | '/app/qualidade/$id'
    | '/app/qualidade/inspecoes'
    | '/app/setor/$setor'
    | '/app/compras'
    | '/app/financeiro'
    | '/app/fiscal'
    | '/app/melhoria'
    | '/app/os'
    | '/app/producao'
    | '/app/qualidade'
    | '/app/reciclaveis'
    | '/app/rh'
    | '/app/seguranca'
    | '/app/vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/$page'
    | '/_authenticated/app/os/$id'
    | '/_authenticated/app/os/nova'
    | '/_authenticated/app/qualidade/$id'
    | '/_authenticated/app/qualidade/inspecoes'
    | '/_authenticated/app/setor/$setor'
    | '/_authenticated/app/compras/'
    | '/_authenticated/app/financeiro/'
    | '/_authenticated/app/fiscal/'
    | '/_authenticated/app/melhoria/'
    | '/_authenticated/app/os/'
    | '/_authenticated/app/producao/'
    | '/_authenticated/app/qualidade/'
    | '/_authenticated/app/reciclaveis/'
    | '/_authenticated/app/rh/'
    | '/_authenticated/app/seguranca/'
    | '/_authenticated/app/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/vendas/': {
      id: '/_authenticated/app/vendas/'
      path: '/app/vendas'
      fullPath: '/app/vendas/'
      preLoaderRoute: typeof AuthenticatedAppVendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/seguranca/': {
      id: '/_authenticated/app/seguranca/'
      path: '/app/seguranca'
      fullPath: '/app/seguranca/'
      preLoaderRoute: typeof AuthenticatedAppSegurancaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/rh/': {
      id: '/_authenticated/app/rh/'
      path: '/app/rh'
      fullPath: '/app/rh/'
      preLoaderRoute: typeof AuthenticatedAppRhIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reciclaveis/': {
      id: '/_authenticated/app/reciclaveis/'
      path: '/app/reciclaveis'
      fullPath: '/app/reciclaveis/'
      preLoaderRoute: typeof AuthenticatedAppReciclaveisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/qualidade/': {
      id: '/_authenticated/app/qualidade/'
      path: '/app/qualidade'
      fullPath: '/app/qualidade/'
      preLoaderRoute: typeof AuthenticatedAppQualidadeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/producao/': {
      id: '/_authenticated/app/producao/'
      path: '/app/producao'
      fullPath: '/app/producao/'
      preLoaderRoute: typeof AuthenticatedAppProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/os/': {
      id: '/_authenticated/app/os/'
      path: '/app/os'
      fullPath: '/app/os/'
      preLoaderRoute: typeof AuthenticatedAppOsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/melhoria/': {
      id: '/_authenticated/app/melhoria/'
      path: '/app/melhoria'
      fullPath: '/app/melhoria/'
      preLoaderRoute: typeof AuthenticatedAppMelhoriaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fiscal/': {
      id: '/_authenticated/app/fiscal/'
      path: '/app/fiscal'
      fullPath: '/app/fiscal/'
      preLoaderRoute: typeof AuthenticatedAppFiscalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/financeiro/': {
      id: '/_authenticated/app/financeiro/'
      path: '/app/financeiro'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/compras/': {
      id: '/_authenticated/app/compras/'
      path: '/app/compras'
      fullPath: '/app/compras/'
      preLoaderRoute: typeof AuthenticatedAppComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/setor/$setor': {
      id: '/_authenticated/app/setor/$setor'
      path: '/app/setor/$setor'
      fullPath: '/app/setor/$setor'
      preLoaderRoute: typeof AuthenticatedAppSetorSetorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/qualidade/inspecoes': {
      id: '/_authenticated/app/qualidade/inspecoes'
      path: '/app/qualidade/inspecoes'
      fullPath: '/app/qualidade/inspecoes'
      preLoaderRoute: typeof AuthenticatedAppQualidadeInspecoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/qualidade/$id': {
      id: '/_authenticated/app/qualidade/$id'
      path: '/app/qualidade/$id'
      fullPath: '/app/qualidade/$id'
      preLoaderRoute: typeof AuthenticatedAppQualidadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/os/nova': {
      id: '/_authenticated/app/os/nova'
      path: '/app/os/nova'
      fullPath: '/app/os/nova'
      preLoaderRoute: typeof AuthenticatedAppOsNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/os/$id': {
      id: '/_authenticated/app/os/$id'
      path: '/app/os/$id'
      fullPath: '/app/os/$id'
      preLoaderRoute: typeof AuthenticatedAppOsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/$page': {
      id: '/_authenticated/app/admin/$page'
      path: '/app/admin/$page'
      fullPath: '/app/admin/$page'
      preLoaderRoute: typeof AuthenticatedAppAdminPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminPageRoute: typeof AuthenticatedAppAdminPageRoute
  AuthenticatedAppOsIdRoute: typeof AuthenticatedAppOsIdRoute
  AuthenticatedAppOsNovaRoute: typeof AuthenticatedAppOsNovaRoute
  AuthenticatedAppQualidadeIdRoute: typeof AuthenticatedAppQualidadeIdRoute
  AuthenticatedAppQualidadeInspecoesRoute: typeof AuthenticatedAppQualidadeInspecoesRoute
  AuthenticatedAppSetorSetorRoute: typeof AuthenticatedAppSetorSetorRoute
  AuthenticatedAppComprasIndexRoute: typeof AuthenticatedAppComprasIndexRoute
  AuthenticatedAppFinanceiroIndexRoute: typeof AuthenticatedAppFinanceiroIndexRoute
  AuthenticatedAppFiscalIndexRoute: typeof AuthenticatedAppFiscalIndexRoute
  AuthenticatedAppMelhoriaIndexRoute: typeof AuthenticatedAppMelhoriaIndexRoute
  AuthenticatedAppOsIndexRoute: typeof AuthenticatedAppOsIndexRoute
  AuthenticatedAppProducaoIndexRoute: typeof AuthenticatedAppProducaoIndexRoute
  AuthenticatedAppQualidadeIndexRoute: typeof AuthenticatedAppQualidadeIndexRoute
  AuthenticatedAppReciclaveisIndexRoute: typeof AuthenticatedAppReciclaveisIndexRoute
  AuthenticatedAppRhIndexRoute: typeof AuthenticatedAppRhIndexRoute
  AuthenticatedAppSegurancaIndexRoute: typeof AuthenticatedAppSegurancaIndexRoute
  AuthenticatedAppVendasIndexRoute: typeof AuthenticatedAppVendasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminPageRoute: AuthenticatedAppAdminPageRoute,
  AuthenticatedAppOsIdRoute: AuthenticatedAppOsIdRoute,
  AuthenticatedAppOsNovaRoute: AuthenticatedAppOsNovaRoute,
  AuthenticatedAppQualidadeIdRoute: AuthenticatedAppQualidadeIdRoute,
  AuthenticatedAppQualidadeInspecoesRoute:
    AuthenticatedAppQualidadeInspecoesRoute,
  AuthenticatedAppSetorSetorRoute: AuthenticatedAppSetorSetorRoute,
  AuthenticatedAppComprasIndexRoute: AuthenticatedAppComprasIndexRoute,
  AuthenticatedAppFinanceiroIndexRoute: AuthenticatedAppFinanceiroIndexRoute,
  AuthenticatedAppFiscalIndexRoute: AuthenticatedAppFiscalIndexRoute,
  AuthenticatedAppMelhoriaIndexRoute: AuthenticatedAppMelhoriaIndexRoute,
  AuthenticatedAppOsIndexRoute: AuthenticatedAppOsIndexRoute,
  AuthenticatedAppProducaoIndexRoute: AuthenticatedAppProducaoIndexRoute,
  AuthenticatedAppQualidadeIndexRoute: AuthenticatedAppQualidadeIndexRoute,
  AuthenticatedAppReciclaveisIndexRoute: AuthenticatedAppReciclaveisIndexRoute,
  AuthenticatedAppRhIndexRoute: AuthenticatedAppRhIndexRoute,
  AuthenticatedAppSegurancaIndexRoute: AuthenticatedAppSegurancaIndexRoute,
  AuthenticatedAppVendasIndexRoute: AuthenticatedAppVendasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
