/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppQualidadeIndexRouteImport } from './routes/_authenticated/app.qualidade.index'
import { Route as AuthenticatedAppOsIndexRouteImport } from './routes/_authenticated/app.os.index'
import { Route as AuthenticatedAppSetorSetorRouteImport } from './routes/_authenticated/app.setor.$setor'
import { Route as AuthenticatedAppOsNovaRouteImport } from './routes/_authenticated/app.os.nova'
import { Route as AuthenticatedAppOsIdRouteImport } from './routes/_authenticated/app.os.$id'
import { Route as AuthenticatedAppAdminPageRouteImport } from './routes/_authenticated/app.admin.$page'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppQualidadeIndexRoute =
  AuthenticatedAppQualidadeIndexRouteImport.update({
    id: '/app/qualidade/',
    path: '/app/qualidade/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOsIndexRoute = AuthenticatedAppOsIndexRouteImport.update({
  id: '/app/os/',
  path: '/app/os/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSetorSetorRoute =
  AuthenticatedAppSetorSetorRouteImport.update({
    id: '/app/setor/$setor',
    path: '/app/setor/$setor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOsNovaRoute = AuthenticatedAppOsNovaRouteImport.update({
  id: '/app/os/nova',
  path: '/app/os/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppOsIdRoute = AuthenticatedAppOsIdRouteImport.update({
  id: '/app/os/$id',
  path: '/app/os/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminPageRoute =
  AuthenticatedAppAdminPageRouteImport.update({
    id: '/app/admin/$page',
    path: '/app/admin/$page',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/$page': typeof AuthenticatedAppAdminPageRoute
  '/app/os/$id': typeof AuthenticatedAppOsIdRoute
  '/app/os/nova': typeof AuthenticatedAppOsNovaRoute
  '/app/setor/$setor': typeof AuthenticatedAppSetorSetorRoute
  '/app/os/': typeof AuthenticatedAppOsIndexRoute
  '/app/qualidade/': typeof AuthenticatedAppQualidadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/$page': typeof AuthenticatedAppAdminPageRoute
  '/app/os/$id': typeof AuthenticatedAppOsIdRoute
  '/app/os/nova': typeof AuthenticatedAppOsNovaRoute
  '/app/setor/$setor': typeof AuthenticatedAppSetorSetorRoute
  '/app/os': typeof AuthenticatedAppOsIndexRoute
  '/app/qualidade': typeof AuthenticatedAppQualidadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/$page': typeof AuthenticatedAppAdminPageRoute
  '/_authenticated/app/os/$id': typeof AuthenticatedAppOsIdRoute
  '/_authenticated/app/os/nova': typeof AuthenticatedAppOsNovaRoute
  '/_authenticated/app/setor/$setor': typeof AuthenticatedAppSetorSetorRoute
  '/_authenticated/app/os/': typeof AuthenticatedAppOsIndexRoute
  '/_authenticated/app/qualidade/': typeof AuthenticatedAppQualidadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/'
    | '/app/admin/$page'
    | '/app/os/$id'
    | '/app/os/nova'
    | '/app/setor/$setor'
    | '/app/os/'
    | '/app/qualidade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/admin/$page'
    | '/app/os/$id'
    | '/app/os/nova'
    | '/app/setor/$setor'
    | '/app/os'
    | '/app/qualidade'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/$page'
    | '/_authenticated/app/os/$id'
    | '/_authenticated/app/os/nova'
    | '/_authenticated/app/setor/$setor'
    | '/_authenticated/app/os/'
    | '/_authenticated/app/qualidade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/qualidade/': {
      id: '/_authenticated/app/qualidade/'
      path: '/app/qualidade'
      fullPath: '/app/qualidade/'
      preLoaderRoute: typeof AuthenticatedAppQualidadeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/os/': {
      id: '/_authenticated/app/os/'
      path: '/app/os'
      fullPath: '/app/os/'
      preLoaderRoute: typeof AuthenticatedAppOsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/setor/$setor': {
      id: '/_authenticated/app/setor/$setor'
      path: '/app/setor/$setor'
      fullPath: '/app/setor/$setor'
      preLoaderRoute: typeof AuthenticatedAppSetorSetorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/os/nova': {
      id: '/_authenticated/app/os/nova'
      path: '/app/os/nova'
      fullPath: '/app/os/nova'
      preLoaderRoute: typeof AuthenticatedAppOsNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/os/$id': {
      id: '/_authenticated/app/os/$id'
      path: '/app/os/$id'
      fullPath: '/app/os/$id'
      preLoaderRoute: typeof AuthenticatedAppOsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/$page': {
      id: '/_authenticated/app/admin/$page'
      path: '/app/admin/$page'
      fullPath: '/app/admin/$page'
      preLoaderRoute: typeof AuthenticatedAppAdminPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminPageRoute: typeof AuthenticatedAppAdminPageRoute
  AuthenticatedAppOsIdRoute: typeof AuthenticatedAppOsIdRoute
  AuthenticatedAppOsNovaRoute: typeof AuthenticatedAppOsNovaRoute
  AuthenticatedAppSetorSetorRoute: typeof AuthenticatedAppSetorSetorRoute
  AuthenticatedAppOsIndexRoute: typeof AuthenticatedAppOsIndexRoute
  AuthenticatedAppQualidadeIndexRoute: typeof AuthenticatedAppQualidadeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminPageRoute: AuthenticatedAppAdminPageRoute,
  AuthenticatedAppOsIdRoute: AuthenticatedAppOsIdRoute,
  AuthenticatedAppOsNovaRoute: AuthenticatedAppOsNovaRoute,
  AuthenticatedAppSetorSetorRoute: AuthenticatedAppSetorSetorRoute,
  AuthenticatedAppOsIndexRoute: AuthenticatedAppOsIndexRoute,
  AuthenticatedAppQualidadeIndexRoute: AuthenticatedAppQualidadeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
